spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:  GMT+8
  flyway:
    url: jdbc:postgresql://onlinemall-db:5432/sales
    user: postgres
    password: 123456
    driver: org.postgresql.Drive
    url: jdbc:mysql://rm-2ze193v2lpi386v8j1o.mysql.rds.aliyuncs.com:3306/sales_db
    user: dbadmin
    password: P@ssw0rd
    driver: com.mysql.jdbc.Driver
    locations: classpath:db/migration # 指定sql文件存放的目录
    baselineOnMigrate: true
  datasource: ## 其他参数就不配置了
    url: jdbc:postgresql://onlinemall-db:5432/sales
    username: postgres
    password: 123456
    url: jdbc:mysql://rm-2ze193v2lpi386v8j1o.mysql.rds.aliyuncs.com:3306/sales_db
    username: dbadmin
    password: P@ssw0rd
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
wx:
  mp:
    appId: wx958544ec24fb775c
    secret: bc732e65c553a6f1f805b18471a83d38
axon:
  axonserver:
    enabled: true
logging:
  config: classpath:logback-spring.xml
server:
  port: 8080
api:
  stockDeduction: http://onlinemall-proxy:8000/product-api/api/product/{1}/stock/deduction