spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:  GMT+8
  flyway:
    url: jdbc:mysql://rm-2ze193v2lpi386v8j1o.mysql.rds.aliyuncs.com:3306/product
    user: dbadmin
    password: P@ssw0rd
    driver: com.mysql.jdbc.Driver
    locations: classpath:db/migration # 指定sql文件存放的目录
    baselineOnMigrate: true
  datasource: ## 其他参数就不配置了
    url: jdbc:mysql://rm-2ze193v2lpi386v8j1o.mysql.rds.aliyuncs.com:3306/product
    driver: com.mysql.jdbc.Driver
    username: dbadmin
    password: P@ssw0rd
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    enabled: true
    servers: onlinemall-axonserver
logging:
  config: classpath:logback-spring.xml
server:
  port: 8080