CREATE TABLE IF NOT EXISTS T_CATALOG (
	CATALOGID varchar(64) PRIMARY KEY NOT NULL,
	CATALOGNAME varchar(64) NOT NULL,
	DESCRIPTION text,
	ORDERNUM INT,
	PARENTID VARCHAR(64) NOT NULL,
	STATUS INT,
	CREATETIME timestamp default now(),
	LASTMODIFIEDTIME timestamp,
	MODIFIER varchar(64)
);
CREATE TABLE IF NOT EXISTS T_PRODUCT (
	PRODUCTID varchar(64) PRIMARY KEY NOT NULL,
	PRODUCTNAME VARCHAR(64) NOT NULL,
	SHORTDESC	VARCHAR(128),
	FULLDESC TEXT,
	THUMBNAIL VARCHAR(256),
	CATALOGID VARCHAR(64) NOT NULL,
	STATUS INT,
	CREATETIME timestamp default now(),
	LASTMODIFIEDTIME timestamp,
	MODIFIER VARCHAR(64)
);