CREATE TABLE IF NOT EXISTS T_ORDER (
	ORDERID CHARACTER VARYING(64) NOT NULL,
	OPENID CHARACTER VARYING(64) NOT NULL,
	SHIPPINGID CHARACTER VARYING(64) NOT NULL,
	PAYMENT NUMERIC(19,2),
	POSTAGE NUMERIC(19,2),
	TOTALAMOUNT NUMERIC(19,2),
	PAYMENTTIME TIMESTAMP,
	SENDTIME TIMESTAMP,
	ENDTIME TIMESTAMP,
	CLOSETIME TIMESTAMP,
	STATUS INTEGER,
	CREATETIME TIMESTAMP DEFAULT NOW(),
	LASTMODIFIEDTIME TIMESTAMP,
	MODIFIER CHARACTER VARYING(64),
	PRIMARY KEY(ORDERID)
);
CREATE TABLE IF NOT EXISTS T_ORDER_PRODUCT(
  ID CHARACTER VARYING(64) PRIMARY KEY,
  ORDERID CHARACTER VARYING(64) NOT NULL,
  PRODUCTID CHARACTER VARYING(64) NOT NULL,
  PRODUCTNAME TEXT NOT NULL,
  UNITPRICE NUMERIC (19,2) NOT NULL,
  QUANLITY INT NOT NULL,
  TOTALPRICE NUMERIC (19,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS T_SHIPPING(
  ID CHARACTER VARYING(64) PRIMARY KEY ,
  OPENID CHARACTER VARYING(64) NOT NULL,
  RECEIVER CHARACTER VARYING(64) NOT NULL,
  PHONE CHARACTER VARYING(64) NOT NULL,
  PROVINCE CHARACTER VARYING(64) NOT NULL,
  CITY CHARACTER VARYING(64) NOT NULL,
  ADDRESS TEXT NOT NULL,
  ZIP CHARACTER VARYING(6),
  CREATETIME TIMESTAMP DEFAULT NOW()
);