version: '3.4'
services:
  postgresql:
    image: postgres:9.6
    container_name: onlinemall-db
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: 123456
    volumes: 
      - /data/dbdata:/var/lib/postgresql/data
    restart: always
  axonserver:
   build:
     context: axon-server
     dockerfile: Dockerfile
   container_name: onlinemall-axonserver
   ports:
     - "8024:8024"
     - "8124:8124"
   environment:
     AXONIQ_AXONSERVER_EVENT_STORAGE: /data
     AXONIQ_AXONSERVER_SNAPSHOT_STORAGE: /data
   volumes:
     - /data/axondata:/data
   restart: always
  product:
    build:
      context: product
      dockerfile: Dockerfile
    container_name: onlinemall-product
    restart: always
  sales:
    build:
      context: sales
      dockerfile: Dockerfile
    container_name: onlinemall-sales
    restart: always
  nginx:
    image: nginx
    container_name: onlinemall-proxy
    ports:
    - "80:80"
    volumes: 
      - ./log:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
    restart: always
#    depends_on:
#      - sales
#      - product
networks:
  default:
    external:
      name: docker_default